name: openpc

services:
  postgres:
    image: postgres:15
    container_name: openpc-postgres
    environment:
      POSTGRES_USER: openpc
      POSTGRES_PASSWORD: openpc
      POSTGRES_DB: openpc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openpc-network
    restart: always

volumes:
  postgres_data:

networks:
  openpc-network:
    driver: bridge