name: coreform

services:
  server:
    build: ./server
    container_name: coreform-server
    env_file:
      - ./server/.env 
    networks:
      - coreform-network
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  db:
    image: postgres:15
    container_name: coreform-postgres
    environment:
      POSTGRES_USER: coreform
      POSTGRES_PASSWORD: coreform
      POSTGRES_DB: coreform
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coreform-network
    restart: always

volumes:
  postgres_data:

networks:
  coreform-network:
    driver: bridge
