import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono, Orbitron } from "@/src/shared/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${Orbitron.variable} h-full antialiased`}
    >
      <body className={`${Orbitron.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
