import { spaceGrotesk } from "@/src/shared/fonts";
import Navbar from "@/src/widgets/navbar/ui";
import Footer from "@/src/widgets/footer/ui";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} h-full antialiased ${spaceGrotesk.className}`}
    >
      <body className={`min-h-full flex flex-col`}>
        <Navbar />

        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
};