
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/1783250425037_gaming_pc.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_7.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_8.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_9.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_10.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_11.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_12.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_13.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_14.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_15.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_16.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_17.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_18.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_19.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_20.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_21.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_22.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_23.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_24.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_25.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_26.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_27.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_28.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_29.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_30.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_31.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_32.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_33.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_34.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_35.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_36.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_37.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_38.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_39.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_40.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_41.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_42.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_43.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_44.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_45.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_46.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_47.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_48.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_49.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_50.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_51.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_52.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_53.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_54.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_55.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_56.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_57.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_58.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_59.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_60.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_61.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_62.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_63.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_64.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_65.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_66.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_67.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_68.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_69.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_70.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_71.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_72.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_73.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_74.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_75.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_76.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_77.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_78.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_79.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_80.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_81.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_82.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_83.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_84.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_85.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_86.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_87.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_88.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_89.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_90.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_91.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_92.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_93.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_94.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_95.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_96.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_97.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_98.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_99.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_100.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_101.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_102.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_103.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_104.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_105.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_106.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_107.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_108.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_109.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_110.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_111.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_112.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_113.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_114.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_115.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_116.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_117.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_118.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_119.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_120.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_121.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_122.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_123.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_124.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_125.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_126.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_127.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_128.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_129.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_130.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_131.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_132.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_133.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_134.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_135.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_136.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_137.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_138.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_139.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_140.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_141.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_142.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_143.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_144.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_145.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_146.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_147.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_148.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_149.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_150.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_151.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_152.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_153.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_154.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_155.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_156.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_157.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_158.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_159.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_160.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_161.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_162.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_163.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_164.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_165.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_166.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_167.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_168.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_169.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_170.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_171.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_172.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_173.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_174.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_175.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_176.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_177.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_178.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_179.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_180.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_181.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_182.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_183.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_184.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_185.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_186.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_187.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_188.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_189.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_190.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_191.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_192.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_193.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_194.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_195.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_196.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_197.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_198.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_199.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_200.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_201.geometry}
            material={materials.texturedFacets}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_202.geometry}
            material={materials.texturedFacets}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/1783250425037_gaming_pc.glb')