import Joi from 'joi';

export const create_model_schema = Joi.object({
    name: Joi.string().required(),
    type: Joi.string().required(),
    brand: Joi.string().required(),
    price: Joi.number().required(),
    image: Joi.string().required(),
    model_file: Joi.string().required(),
    model_code_file: Joi.string().required(),
    cordinations: Joi.object({
        id: Joi.string().uuid(),
        cpu_cordination_x: Joi.string().required(),
        cpu_cordination_y: Joi.string().required(),
        cpu_cordination_z: Joi.string().required(),
        gpu_cordination_x: Joi.string().required(),
        gpu_cordination_y: Joi.string().required(),
        gpu_cordination_z: Joi.string().required(),
        mother_board_cordination_x: Joi.string().required(),
        mother_board_cordination_y: Joi.string().required(),
        mother_board_cordination_z: Joi.string().required(),
        ram_cordination_x: Joi.string().required(),
        ram_cordination_y: Joi.string().required(),
        ram_cordination_z: Joi.string().required(),
        storage_cordination_x: Joi.string().required(),
        storage_cordination_y: Joi.string().required(),
        storage_cordination_z: Joi.string().required(),
        power_supply_cordination_x: Joi.string().required(),
        power_supply_cordination_y: Joi.string().required(),
        power_supply_cordination_z: Joi.string().required(),
        cooler_cordination_x: Joi.string().required(),
        cooler_cordination_y: Joi.string().required(),
        cooler_cordination_z: Joi.string().required(),
        case_model_id: Joi.string().uuid().required(),
    }).optional()
});

export const update_model_schema = Joi.object({
    id: Joi.string().uuid(),
    name: Joi.string().optional(),
    type: Joi.string().optional(),
    brand: Joi.string().optional(),
    price: Joi.number().optional(),
    image: Joi.string().optional(),
    model_file: Joi.string().optional(),
    model_code_file: Joi.string().optional(),
    cordinations: Joi.object({
        id: Joi.string().uuid(),
        cpu_cordination_x: Joi.string().optional(),
        cpu_cordination_y: Joi.string().optional(),
        cpu_cordination_z: Joi.string().optional(),
        gpu_cordination_x: Joi.string().optional(),
        gpu_cordination_y: Joi.string().optional(),
        gpu_cordination_z: Joi.string().optional(),
        mother_board_cordination_x: Joi.string().optional(),
        mother_board_cordination_y: Joi.string().optional(),
        mother_board_cordination_z: Joi.string().optional(),
        ram_cordination_x: Joi.string().optional(),
        ram_cordination_y: Joi.string().optional(),
        ram_cordination_z: Joi.string().optional(),
        storage_cordination_x: Joi.string().optional(),
        storage_cordination_y: Joi.string().optional(),
        storage_cordination_z: Joi.string().optional(),
        power_supply_cordination_x: Joi.string().optional(),
        power_supply_cordination_y: Joi.string().optional(),
        power_supply_cordination_z: Joi.string().optional(),
        cooler_cordination_x: Joi.string().optional(),
        cooler_cordination_y: Joi.string().optional(),
        cooler_cordination_z: Joi.string().optional(),
        case_model_id: Joi.string().uuid().optional(),
    }).optional()
});