"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: salvatore.butera1998 (https://sketchfab.com/salvatore.butera1998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-computer-graphics-1f4333241f7b4de5a7aa0f3dc9eae3e2
Title: PC - Computer graphics
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
    const { nodes, materials } = useGLTF('/models/pc_-_computer_graphics.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0.231, 0.371, 0.023]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.AMD_material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.AMDCenter}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials.Metallic}
                />
            </group>
            <group position={[0.09, 0.264, -0.015]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.RTX_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.Metallic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials.Plastic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.Plastic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials.Emission}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.Silicio}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.material}
                />
            </group>
            <group position={[0.297, 0.37, 0.018]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials.RoughPlastic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.Silicio}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials.material}
                />
            </group>
            <group position={[0.308, 0.37, 0.018]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials.RoughPlastic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials.Silicio}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials.material}
                />
            </group>
            <group position={[0.319, 0.37, 0.018]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials.RoughPlastic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.Silicio}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials.material}
                />
            </group>
            <group position={[0.328, 0.37, 0.018]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_34.geometry}
                    material={materials.RoughPlastic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_35.geometry}
                    material={materials.Silicio}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials.material}
                />
            </group>
            <group position={[0.194, 0.281, -0.017]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_38.geometry}
                    material={materials.Motherboard}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_39.geometry}
                    material={materials.RTX_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials.MotherBoardEmission}
                />
            </group>
            <group position={[0.415, 0.265, -0.015]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_46.geometry}
                    material={materials.RTX_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_47.geometry}
                    material={materials.Plastic}
                />
            </group>
            <group position={[0.128, 0.187, 0.007]} rotation={[-Math.PI, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_53.geometry}
                    material={materials.MotherboardRetro}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_54.geometry}
                    material={materials.material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_55.geometry}
                    material={materials.RTX_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_56.geometry}
                    material={materials.material_13}
                />
            </group>
            <group position={[0.231, 0.371, 0.023]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_62.geometry}
                    material={materials.AMD_material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_63.geometry}
                    material={materials.AMDCenter}
                />
            </group>
            <group position={[0.108, 0.396, 0.108]} scale={1.24}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_67.geometry}
                    material={materials.material_15}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_68.geometry}
                    material={materials.Case}
                />
            </group>
            <group position={[0.092, 0.432, -0.073]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_78.geometry}
                    material={materials.RTX_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_79.geometry}
                    material={materials.material_15}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials.AMD_material}
                position={[0.231, 0.371, 0.023]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_18.geometry}
                material={materials.MotherboardRetro}
                position={[0.237, 0.324, -0.007]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials.RTX_Material}
                position={[0.092, 0.433, -0.073]}
                rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_42.geometry}
                material={materials.Motherboard}
                position={[0.196, 0.281, -0.018]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_44.geometry}
                material={materials.Motherboard}
                position={[0.254, 0.243, 0.1]}
                rotation={[Math.PI / 2, 0, -0.226]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_49.geometry}
                material={materials.Cable}
                position={[0.259, 0.246, 0.121]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_51.geometry}
                material={materials.Motherboard}
                position={[0.256, 0.244, 0.109]}
                rotation={[Math.PI / 2, 0, -0.071]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_58.geometry}
                material={materials.material_14}
                position={[0.168, 0.112, 0.052]}
                scale={1.156}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_60.geometry}
                material={materials.material_15}
                position={[0.219, 0.109, 0.007]}
                scale={[0.897, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_65.geometry}
                material={materials.Case}
                position={[0.094, 0.396, 0.11]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={[1.001, 0.584, 1.001]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_70.geometry}
                material={materials.Case}
                position={[0.089, 0.457, 0.167]}
                scale={0.67}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_72.geometry}
                material={materials.Case}
                position={[0.108, 0.396, 0.11]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.06}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_74.geometry}
                material={materials.RTX_Material}
                position={[0.092, 0.433, -0.073]}
                rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_76.geometry}
                material={materials.RTX_Material}
                position={[0.092, 0.43, -0.073]}
                rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_81.geometry}
                material={materials.Metallic}
                position={[0.485, 0.475, 0.03]}
                rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_83.geometry}
                material={materials.Metallic}
                position={[0.092, 0.432, -0.073]}
                rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_85.geometry}
                material={materials.RTX_Material}
                position={[0.452, 0.467, 0.042]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.457}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_87.geometry}
                material={materials.Metallic}
                position={[0.485, 0.475, 0.02]}
                rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_89.geometry}
                material={materials.Metallic}
                position={[0.092, 0.432, -0.082]}
                rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_91.geometry}
                material={materials.Plastic}
                position={[0.254, 0.243, 0.105]}
                rotation={[Math.PI / 2, 0, -0.226]}
            />
        </group>
    )
}

useGLTF.preload('/models/pc_-_computer_graphics.glb')
